### PR TITLE
Date range should be auto set with pre-set start and end date

### LINKED ISSUE #4: Date range is not automatically set
When a start and end date are provided to the directive, the date range is not set automatically. This causes the green highlighting to not show up until the user has selected a new start and end date.

Current Functionality
screen shot 2015-04-09 at 2 41 49 pm
v.s.
Desired Functionality
screen shot 2015-04-09 at 2 41 55 pm

### PR DESCRIPTION
**Pull request by chadfawcett**
Resolves #4

### CODE REVIEW

**Comment by chadfawcett** [comment]
It appears we need to set up some sort of watchers as well on the start and end date. That way if the start and end date are set elsewhere (i.e. with the quick select buttons) the calendar shows the correct date range.

**Comment by jonotron** [comment]
Ya, makes sense. If you can add the `$watch` to update the range then I will merge.

**Comment by chadfawcett** [comment]
@jonotron Should be good to go now.

**Comment by jonotron** [comment]
:+1:

**Pull request merged**
